version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pelni_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pelni_user
      POSTGRES_PASSWORD: Pelni2025
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pelni_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
